version: '3'
services:
  app:
    build: .
    volumes:
      - ".:/home/node/app"
      - ".docker/zsh/.p10k.zsh:/home/node/.p10k.zsh:delegated"
      - ".docker/zsh/history:/home/node/zsh:delegated"
    container_name: fullcycle-app-typescript
